### ISSUE TITLE
SignalK  Data to Windy conversions

### ISSUE THREAD

**Issue by ckcrs** [itemir/signalk-windy#2]
Thanks for the plugin, just started to use.
I **cannot see my humidity and pressure data on windy's PWS.** 
Hope my thoughts are  not wrong:
1. environment.outside.humidity unit is ratio in SignalK (50% shown as 0.5) Hence windy cannot show 0.5 ratio as 50% red. hum.  Prior to data submission to windy, signalK value need to be multiplied by 100, I think?
2. Another one may be about environment.outside.pressure? As Pa for SignalK default, again there may be a SignalK to windy conversion required?
Thanks,Sancan

**Comment by itemir** [comment]
Hi Sancan,

Thanks. Item 1 makes sense, I actually noticed this in a different case recently but I don't follow 2. I think Windy actually processes Pascals. Here is a sample station: https://www.windy.com/RPVJ?12.370,122.531,8,i:pressure

Do you see differently? What is your station ID?

**Comment by ckcrs** [comment]
Hello Ilker,
My station id 64f07cf7d9. in windy I see hPa, mmH or inHg as pressure unit, and no pressure data though I can see on signalK as Pa.
Do you have a solution for correct wind direction, if boat still, then COG is not true only heading with my setup, so the wind direction also reported to and displayed in windy wrong?
Regards

**Comment by itemir** [comment]
So there is an option for "Use true wind speed and direction (as opposed to apparent)", you can use it to adjust based where your wind sensor resides. 

I don't think the problem is with the pressure readings, I suspect it is something else. Are you certain you have the wind readings?

BTW, I have a separate solution that I am looking testers for. If you install that plugin it can help me understand what is happening here more too. You need to install the "signalk-saillogger" plugin and create a free account on saillogger.com. Let me know if you test it out.

**Comment by ckcrs** [comment]
1- "So there is an option for "Use true wind speed and direction (as opposed to apparent)", you can use it to adjust based where your wind sensor resides."
Sorry, I did not understand above, you mean already an existing option ( I don't see it in plugin) or a proposed solution? Meanwhile it may be related with my stationary boat with wrong COG values of gps, resulting wrong TWD. I did something in signal to sort out and testing now...
2- I just setup and started to see some of my boat data (named Puff) on monitoring tool of sailloger: COG, wind speed & direction, humidity, depth, water temp, outside temp is there, but no battery voltage?

**Comment by itemir** [comment]
On 1, yes, it is already there:  [Screenshot](https://www.ilkertemir.com/ecowitt_config.png)

On 2, please see question 7 on [Saillogger FAQ](https://saillogger.com/faq/).

**Comment by ckcrs** [comment]
Set it up in sail logger as boat name Puff.
Screenshot points Ecowitt GW1000 not windy plugin? I'm not using Ecowitt.
Battery ok now.
Thanks, 
ps:wind is also ok after I corrected my setup for Two...

**Comment by itemir** [comment]
Sorry, too many plugins to think about. 

Glad to hear it works, let me know if there are any other issues.

**Comment by itemir** [comment]
I juts published a v0.0.4 of the plugin. This should address humidity issues and other issues that may be outstanding. I will close this, please re-open if issues persist.
